# Data with a record count of > 50K or 
# highly dimensional data

schema_version: "1.0"
name: "high-dimensionality"
models:
  - ctgan:
        data_source: __tmp__
        params:
            epochs: 300
            generator_dim: [256, 256]
            discriminator_dim: [256, 256]
            generator_lr: 2e-4
            discriminator_lr: .00001
            batch_size: 500
            verbose: true
        # Gretel privacy filtering
        privacy_filters:
            outliers: null
            similarity: high
